account/urls.py
from django.urls import path , include
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name= 'signup'),
    path('profile/', views.profile, name= 'profile'),
    path('profile/edit/', views.edit_profile, name= 'edit_profile'),
]

job/urls.py
from django.urls import path , include
from . import views
from . import api


app_name = 'job'
urlpatterns = [

    path('',views.job_list, name='job_list'), 
    path('add_job', views.add_job, name='add_job'),
    path('<str:slug>',views.job_detail , name= 'job_detail'),# the id of the job 

    ## api
    path('api/', api.job_list_api, name='job_list_api'),
    path('api/<int:id>/', api.job_detail_api, name='job_detail_api'),

    ## class based view
    path('v2/api/', api.JobListApi.as_view(), name='JobListApi'),
    path('v2/api/<int:id>/', api.JobDetailApi.as_view(), name='Job_Detail_Api'),        
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls' , namespace= 'accounts')),
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls', namespace='jobs')),
    path('contact-us/', include('contact.urls', namespace='contact')),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.db.models.fields.related import OneToOneField
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
    user  = models.OneToOneField(User, on_delete=models.CASCADE)
    city  = models.ForeignKey('City', name= 'city', on_delete=models.CASCADE, null=True, blank=True)
    phone_number = models.CharField(max_length=25)
    image  = models.ImageField(upload_to='profile/' )

    def __str__(self):
        return str(self.user)

### create new user ----> creat new empty profile
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


class City(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

account/forms.py
from django import forms
from account.models import Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import fields

class SignupForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ['username','email','password1','password2']



class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ('user',)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email']

account/views.py
from django.shortcuts import redirect, render
from .forms import SignupForm
from django.contrib.auth import authenticate, login
from .models import Profile
from .forms import ProfileForm, UserForm
from django.urls import reverse
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('accounts/profile')
    else:
        form = SignupForm()
    context= {
        'form' : form
    }

    return render(request,'registration/signup.html', context)


def profile(request):
    profile = Profile.objects.get(user = request.user)
    return render(request, 'accounts/profile.html', {'profile':profile})


def edit_profile(request):
    profile = Profile.objects.get(user = request.user)
    if request.method == 'POST':
        formuser = UserForm(request.POST,instance=request.user)
        formprofile = ProfileForm(request.POST,request.FILES, instance=profile)
        if formuser.is_valid() and formprofile.is_valid():
            formuser.save()
            myprofile = formprofile.save(commit= False)
            myprofile.user = request.user
            myprofile.save()
            return redirect(reverse('accounts:profile'))
    else :
        formuser = UserForm(instance=request.user)
        formprofile = ProfileForm(instance=profile)

    context = {
        'formuser': formuser,
        'formprofile': formprofile,
    }
    return render(request, 'accounts/edit_profile.html', context)

account/templates/accounts/edit_profile.html
{%extends 'base.html' %}
{% load bootstrap5 %}
    {% block content%}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Edit Profile</h4>
                        <form  method="post" class="form" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form formuser %}
                            {% bootstrap_form formprofile %}
                            {% buttons %}
                                <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                            {% endbuttons %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {%endblock%}

account/templates/accounts/profile.html
{%extends 'base.html' %}
{% load bootstrap5 %}
    {% block content%}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{profile}}</span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <li>Phone: <span>{{profile.phone_number}}</span></li>
                                <li>Address: <span>{{profile.city}}</span></li>

                            </ul>
                            
                        </div>
                        <div class="p-5">
                            <a class="boxed-btn3 w-100" href="{% url 'accounts:edit_profile'%}"> Edit Profile</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {%endblock%}


    <button class="boxed-btn3 w-100" type="submit">Apply Now</button>